version: '2.1'

services:

  kong-database:
    image: cassandra:3
    expose:
      - 9042


#  kong-migration:
#    image: kong
#    depends_on:
#      kong-database:
#        condition: service_healthy
#    environment:
#      - KONG_DATABASE=postgres
#      - KONG_PG_HOST=kong-database
#    command: kong migrations up

  kong:
    image: kong
    depends_on:
      - kong-database

#      kong-migration:
#        condition: service_started
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    expose:
      - 8000
      - 8001
      - 8443
      - 8444